services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=sbdocs'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
  mongodb:
    image: mongo:latest  # Use the latest MongoDB image
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: mongoadmin # Or your preferred username
      MONGO_INITDB_ROOT_PASSWORD: password  # Use a strong password
    ports:
      - "27017:27017"
    labels:
      - "org.springframework.boot.service-connection=mongodb"